---
#  - name: iptables INPUT ACCEPT
#    iptables:
#      chain: INPUT
#      policy: ACCEPT

  - name: iptables established connections
    iptables:
      chain: INPUT
      ctstate: ESTABLISHED,RELATED
      jump: ACCEPT
    notify: save iptables

  - name: iptables localhost
    iptables:
      chain: INPUT
      source: localhost
      jump: ACCEPT
    notify: save iptables

  - name: iptables SSH
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 22
      jump: ACCEPT
    notify: save iptables

  - name: iptables node_exporter
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 9100
      jump: ACCEPT
    notify: save iptables

  - name: iptables INPUT DROP
    iptables:
      chain: INPUT
      policy: DROP
    notify: save iptables

    #   - iptables:
     #chain: INPUT
     #policy: DROP
